# Generated by Django 3.0.5 on 2020-06-22 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tought',
            new_name='thought',
        ),
    ]
